language: python
python:
  - 3.8.6

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/pairanalysis_tests.py
  - python -m unittest tests/Cp_tests.py
  - python -m unittest tests/EOS_fitting_tests.py
  - python -m unittest tests/min_F_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main
